# Generated by Django 4.1.6 on 2023-09-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sales_date_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sales_date_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
