# Generated by Django 4.1.6 on 2023-09-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='search_tags',
            field=models.TextField(blank=True, max_length=2555, null=True),
        ),
    ]
